# src/evaluate.py
#
# PURPOSE:
#   Evaluate the trained WasteLens model on the test set.
#
#   - Reports PER-CLASS precision, recall, and F1 (not just overall accuracy),
#     per the project success criteria.
#   - Produces a confusion matrix to identify which classes the model
#     confuses with each other.
#   - Flags weak-performing classes for the report (docs/report.md).
#
# STATUS: Implemented - loads the best checkpoint (wastelens_ep09.keras,
#   lowest val_loss), reconstructs the IDENTICAL stratified test split used
#   during training (same pipeline, seed=42), runs predictions, reports
#   per-bin precision/recall/F1 + confusion matrix, flags the weakest bin
#   by F1, and writes the full report to docs/report.md.

"""WasteLens evaluation script.

Run from the repo root:
    python src/evaluate.py                      # default checkpoint/report
    python src/evaluate.py --model <path>       # custom checkpoint
    python src/evaluate.py --out <path.md>      # custom report location

The default checkpoint is models/checkpoints/wastelens_ep09.keras (best
epoch by val_loss). Copy it from Colab Drive (MyDrive/WasteLens/models/
checkpoints/) into models/checkpoints/ first, or pass --model directly.
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import tensorflow as tf
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    precision_recall_fscore_support,
)

import train as wl  # same pipeline -> identical split (seed=42)

DEFAULT_MODEL = Path("models/checkpoints/wastelens_ep09.keras")
DEFAULT_REPORT = Path("docs/report.md")

CHECKPOINT_NOTE = (
    "Checkpoint `wastelens_ep09.keras` was selected as the best model by "
    "validation loss (lowest val_loss at epoch 9). Epoch 10 showed early "
    "signs of overfitting (train_loss 0.0157 vs val_loss 0.0779), so the "
    "final epoch was NOT used."
)


# --- Pipeline ----------------------------------------------------------------

def load_trained_model(model_path: Path):
    """Load the selected checkpoint, with a helpful error if it is missing."""
    if not model_path.exists():
        raise FileNotFoundError(
            f"Model checkpoint not found: {model_path}\n"
            "Copy it from Colab/Drive (MyDrive/WasteLens/models/checkpoints/) "
            "into models/checkpoints/, or pass --model <path>."
        )
    print(f"[1/5] Loading model: {model_path}")
    return tf.keras.models.load_model(model_path)


def reconstruct_test_split() -> dict[str, list[tuple[Path, int]]]:
    """Rebuild the EXACT same data pipeline and split as src/train.py."""
    print("[2/5] Reconstructing the training data pipeline (same seed=42 split)")
    dataset_root = wl.download_dataset()
    images = wl.scan_images(dataset_root)
    binned = wl.remap_to_bins(images)
    splits = wl.stratified_split(binned)
    return splits


def predict_bins(model, rows: list[tuple[Path, int]]) -> tuple[np.ndarray, np.ndarray]:
    """Predict on the test rows; returns (y_true, y_pred) index arrays."""
    ds = wl.make_dataset(rows, training=False)  # no shuffle -> order preserved
    print(f"[3/5] Predicting on {len(rows)} held-out test images ...")
    probs = model.predict(ds, verbose=1)
    y_pred = probs.argmax(axis=1)
    y_true = np.asarray([lbl for _, lbl in rows], dtype=int)
    assert len(y_pred) == len(y_true), "prediction/label length mismatch"
    return y_true, y_pred

# --- Metrics and reporting ---------------------------------------------------

def per_bin_metrics(y_true: np.ndarray, y_pred: np.ndarray):
    p, r, f1, sup = precision_recall_fscore_support(
        y_true, y_pred, labels=list(range(len(wl.BINS))), zero_division=0
    )
    return p, r, f1, sup


def build_report_md(
    model_path: Path,
    splits: dict[str, list[tuple[Path, int]]],
    class_weights: dict[int, float],
    y_true: np.ndarray,
    y_pred: np.ndarray,
) -> str:
    """Generate the full markdown report (methodology + results + analysis)."""
    print("[4/5] Computing per-bin metrics and building report")
    p, r, f1, sup = per_bin_metrics(y_true, y_pred)
    cm = confusion_matrix(y_true, y_pred, labels=list(range(len(wl.BINS))))
    acc = accuracy_score(y_true, y_pred)
    macro_f1 = float(np.mean(f1))
    freq = np.bincount(y_true, minlength=len(wl.BINS)) / len(y_true)
    weighted_f1 = float(np.sum(f1 * freq))
    weakest_idx = int(np.argmin(f1))
    weakest_name = wl.BINS[weakest_idx]
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines: list[str] = []
    lines.append("# WasteLens - Project Report")
    lines.append("")
    lines.append(f"*Auto-generated by `src/evaluate.py` on {now}. "
                 "Edit freely; sections 3 and 4 are computed from the test set.*")
    lines.append("")
    lines.append("## 1. Introduction")
    lines.append("")
    lines.append("WasteLens is a browser-based waste/garbage image classifier "
                 "(see PROJECT_BRIEF.md). The user captures or uploads a photo "
                 "and a client-side TensorFlow.js model classifies it into one "
                 "of four bins - recyclable, organic, hazardous, or general "
                 "trash - with a confidence score. This report documents the "
                 "training data, model, and per-class evaluation results.")
    lines.append("")
    lines.append("## 2. Methodology")
    lines.append("")
    lines.append(f"- **Dataset:** Kaggle `{wl.KAGGLE_HANDLE}` (12 classes), "
                 "loaded via kagglehub. Remapped to the 4-bin taxonomy; "
                 "`clothes` and `shoes` dropped. 8,213 usable images.")
    lines.append("- **Class mapping:** cardboard/paper/plastic/metal/"
                 "brown-glass/green-glass/white-glass -> recyclable; "
                 "biological -> organic; battery -> hazardous; "
                 "trash -> general trash (docs/dataset_research.md, section 6).")
    lines.append("- **Split:** stratified 70/15/15 (seed=42); "
                 "train %d / val %d / test %d images."
                 % (len(splits["train"]), len(splits["val"]), len(splits["test"])))
    lines.append("- **Model:** frozen MobileNetV2 (ImageNet) + "
                 "GAP -> Dropout(0.2) -> Dense(256) -> Dropout(0.2) -> "
                 "Dense(4, softmax); 328,964 trainable parameters.")
    lines.append("- **Training:** Adam(1e-3), sparse categorical cross-entropy, "
                 "batch 32, 224x224 inputs preprocessed to [-1, 1], 10 epochs, "
                 "inverse-frequency class weights ("
                 + ", ".join(f"{wl.BINS[i]}={class_weights[i]:.2f}"
                             for i in range(len(wl.BINS)))
                 + ") to counter the ~8:1 imbalance.")
    lines.append(f"- **Selected checkpoint:** {CHECKPOINT_NOTE}")
    lines.append("")
    lines.append("## 3. Results")
    lines.append("")
    lines.append("### 3.1 Per-bin precision / recall / F1 (test set)")
    lines.append("")
    lines.append("| Bin | Precision | Recall | F1 | Test support |")
    lines.append("|-----|----------:|-------:|---:|-------------:|")
    for i, b in enumerate(wl.BINS):
        lines.append(f"| {b} | {p[i]:.4f} | {r[i]:.4f} | {f1[i]:.4f} | "
                     f"{int(sup[i])} |")
    lines.append(f"| **overall** | - | - | accuracy={acc:.4f} | "
                 f"{len(y_true)} |")
    lines.append(f"| **macro avg** | {np.mean(p):.4f} | {np.mean(r):.4f} | "
                 f"{macro_f1:.4f} | {len(y_true)} |")
    lines.append(f"| **weighted avg** | {np.sum(p * freq):.4f} | "
                 f"{np.sum(r * freq):.4f} | {weighted_f1:.4f} | {len(y_true)} |")
    lines.append("")
    lines.append("### 3.2 Confusion matrix (rows = true bin, columns = predicted)")
    lines.append("")
    lines.append("| true \\ pred | " + " | ".join(wl.BINS) + " | total |")
    lines.append("|" + "---|" * (len(wl.BINS) + 2))
    for i, b in enumerate(wl.BINS):
        cells = " | ".join(str(int(v)) for v in cm[i])
        lines.append(f"| **{b}** | {cells} | {int(cm[i].sum())} |")
    lines.append("")
    lines.append("### 3.3 Weakest-performing bin (flagged)")
    lines.append("")
    lines.append(f"> **WEAKEST BIN: `{weakest_name}`** "
                 f"(F1 = {f1[weakest_idx]:.4f}, lowest of all four bins)")
    lines.append("")
    weakest_bin_f1 = f1[weakest_idx]
    weakest_name2 = weakest_name
    row = cm[weakest_idx]
    confusions = sorted(
        ((j, int(row[j])) for j in range(len(wl.BINS)) if j != weakest_idx),
        key=lambda t: -t[1],
    )
    support = int(cm[weakest_idx].sum())
    lines.append("## 4. Weak-Performing Class Analysis")
    lines.append("")
    lines.append(f"The weakest bin by F1 is **{weakest_name2}** "
                 f"(F1 = {weakest_bin_f1:.4f}; precision = "
                 f"{p[weakest_idx]:.4f}, recall = {r[weakest_idx]:.4f}).")
    lines.append("")
    if support > 0:
        lines.append("Where it goes (most frequent confusions):")
        lines.append("")
        for j, n in confusions:
            if n == 0:
                continue
            pct = 100.0 * n / support
            lines.append(f"- true `{weakest_name2}` predicted as "
                         f"`{wl.BINS[j]}`: {n} images "
                         f"({pct:.1f}% of its {support} test images)")
        if all(n == 0 for _, n in confusions):
            lines.append("- no off-diagonal errors in the test set for this bin")
    else:
        lines.append("This bin has no test support in the current split.")
    lines.append("")
    bin_totals = {"recyclable": 5586, "organic": 985,
                  "hazardous": 945, "general trash": 697}
    bin_total = bin_totals[weakest_name2]
    lines.append("Plausible explanation (consistent with "
                 "docs/dataset_research.md, section 5): in the mapped dataset "
                 f"`{weakest_name2}` has {bin_total} images overall "
                 f"({100.0 * bin_total / 8213:.1f}% of the 8,213 usable "
                 "images), versus 5,586 for recyclable - an ~8:1 max/min "
                 "imbalance. Smaller support means the model sees fewer and "
                 "more varied examples of this bin"
                 + (" and, for general trash specifically, it is an open-ended "
                    "catch-all (miscellaneous items that fit no other bin), "
                    "so it overlaps visually with every other class."
                    if weakest_name2 == "general trash" else
                    ". Its items also visually resemble materials from the "
                    "other, better-represented bins.")
                 + " The off-diagonal confusions above show exactly "
                 "which bins it gets mistaken for; training-time class "
                 f"weights already up-weighted it (weight = "
                 f"{class_weights[weakest_idx]:.2f}), which mitigates but "
                 "cannot fully remove the imbalance effect.")
    lines.append("")
    lines.append("## 5. Conclusion")
    lines.append("")
    lines.append(f"On the held-out test set the frozen-backbone transfer model "
                 f"reached accuracy = {acc:.4f} and macro-F1 = {macro_f1:.4f} "
                 f"(weighted-F1 = {weighted_f1:.4f}). The per-class results and "
                 "confusion matrix above satisfy the project success criteria; "
                 "the flagged weak bin and its analysis (section 4) document "
                 "the main limitation.")
    lines.append("")
    return "\n".join(lines)


# --- Orchestration -----------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Evaluate the WasteLens model")
    parser.add_argument("--model", type=Path, default=DEFAULT_MODEL,
                        help="checkpoint path (default: %(default)s)")
    parser.add_argument("--out", type=Path, default=DEFAULT_REPORT,
                        help="report markdown path (default: %(default)s)")
    args = parser.parse_args()

    model = load_trained_model(args.model)
    splits = reconstruct_test_split()
    class_weights = wl.compute_class_weights(splits["train"])  # report context
    y_true, y_pred = predict_bins(model, splits["test"])
    report = build_report_md(args.model, splits, class_weights, y_true, y_pred)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(report, encoding="utf-8")
    print(f"[5/5] Report written to: {args.out}\n")
    print(report)


if __name__ == "__main__":
    main()



